### ISSUE TITLE
Unable to save configuration in gui

### ISSUE THREAD

**Issue by k4nzdroid** [debauchee/barrier#2078]
### What happened?

1) flatpak run com.github.debauchee.barrier
2) In GUI, Barrier > Change Settings > Enable SSL > OK > Ctrl+Q
3) flatpak run com.github.debauchee.barrier
4) For the `Enable SSL`, it is in unchecked.

And `Enable SSL` is only an example, Other options and `Configure Server...` have the same problem. 

Those functions are working properly. It's just unable to persist the configuration after restart.

### Version

v2.4.0

### Git commit hash (if applicable)

Version: 2.4.0-release-3e0d758b ==> From About Barrier

### If applicable, where did you install Barrier from?

Flatpak https://flathub.org/apps/com.github.debauchee.barrier

```
# flatpak remote-info --log flathub  com.github.debauchee.barrier

Barrier - Barrier - Share mouse and keyboard over the local network

        ID: com.github.debauchee.barrier
       Ref: app/com.github.debauchee.barrier/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 2.4.0
   License: GPL-2.0
Collection: org.flathub.Stable
  Download: 3.6 MB
 Installed: 9.1 MB
   Runtime: org.kde.Platform/x86_64/5.15-22.08
       Sdk: org.kde.Sdk/x86_64/5.15-22.08

    Commit: a14f176b7f3ed33f042a225eb45e82d2e5982ceb9e75b8ad1788f0ade1e878ae
    Parent: 9bc30c27817d6ec558df1fe567577e6ea44b5cb04d86cce0b99666a27c2c53b9
   Subject: Drop org.kde.* own-name (41214f2d)
      Date: 2024-01-03 06:11:31 +0000
   History: 

    Commit: 9bc30c27817d6ec558df1fe567577e6ea44b5cb04d86cce0b99666a27c2c53b9
   Subject: [Update] barrier bump to v2.4.0, KDE runtime to 5.15-22.08 (5d65b0b6)
      Date: 2022-11-08 21:11:02 +0000

    Commit: e9789b648057a07e33f9b9f718f56359a93cea1ae5606976ce1f67d47f0dbddd
   Subject: [Update] barrier bump to v2.4.0, KDE runtime to 5.15-22.08 (5d65b0b6)
      Date: 2022-11-08 21:11:02 +0000

    Commit: 391a52eadfd648ccfa5ebf9534c453979b503af7d27e07bdfbf9cb843bbbe200
   Subject: Update Barrier version to v2.3.4 and KDE runtime to 5.15-21.08 (23f695d6)
      Date: 2022-04-23 23:39:06 +0000
```
The version we installed:
```
# flatpak info com.github.debauchee.barrier

Barrier - Barrier - Share mouse and keyboard over the local network

          ID: com.github.debauchee.barrier
         Ref: app/com.github.debauchee.barrier/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.4.0
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 9.1 MB
     Runtime: org.kde.Platform/x86_64/5.15-22.08
         Sdk: org.kde.Sdk/x86_64/5.15-22.08

      Commit: a14f176b7f3ed33f042a225eb45e82d2e5982ceb9e75b8ad1788f0ade1e878ae
      Parent: 9bc30c27817d6ec558df1fe567577e6ea44b5cb04d86cce0b99666a27c2c53b9
     Subject: Drop org.kde.* own-name (41214f2d)
        Date: 2024-01-03 06:11:31 +0000
```

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

```
# lsb_release -d
No LSB modules are available.
Description:	Ubuntu 24.04 LTS
```
And everything is up to date.
```
# sudo apt-get upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-4 grim kbuild libabw-0.1-1 libavahi-compat-libdnssd1 libcddb2 libcdr-0.1-1 libcolamd3 libdvbpsi10 libe-book-0.1-1 libebml5 libeot0 libepubgen-0.1-1 libetonyek-0.1-1 libexttextcat-2.0-0 libexttextcat-data
  libfreehand-0.1-1 libgtksourceview-4-0 libgtksourceview-4-common libgtksourceviewmm-3.0-0v5 libgtkspell3-3-0 libgtkspellmm-3.0-0v5 libkate1 libmad0 libmatroska7 libmspub-0.1-1 libmwaw-0.3-3 libmythes-1.2-0 libodfgen-0.1-1
  libopenmpt-modplug1 liborcus-0.18-0 liborcus-parser-0.18-0 libpagemaker-0.0-0 libproxy-tools libqtspell-qt5-1 libqtspell-qt5-data libresid-builder0c2a librevenge-0.0-0 libsidplay2 libsuitesparseconfig7 libvncclient1 libwpd-0.10-10
  libwpg-0.3-3 libwps-0.4-4 libxml++2.6-2v5 lp-solve module-assistant nvidia-firmware-535-535.171.04
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# sudo apt-get dist-upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-4 grim kbuild libabw-0.1-1 libavahi-compat-libdnssd1 libcddb2 libcdr-0.1-1 libcolamd3 libdvbpsi10 libe-book-0.1-1 libebml5 libeot0 libepubgen-0.1-1 libetonyek-0.1-1 libexttextcat-2.0-0 libexttextcat-data
  libfreehand-0.1-1 libgtksourceview-4-0 libgtksourceview-4-common libgtksourceviewmm-3.0-0v5 libgtkspell3-3-0 libgtkspellmm-3.0-0v5 libkate1 libmad0 libmatroska7 libmspub-0.1-1 libmwaw-0.3-3 libmythes-1.2-0 libodfgen-0.1-1
  libopenmpt-modplug1 liborcus-0.18-0 liborcus-parser-0.18-0 libpagemaker-0.0-0 libproxy-tools libqtspell-qt5-1 libqtspell-qt5-data libresid-builder0c2a librevenge-0.0-0 libsidplay2 libsuitesparseconfig7 libvncclient1 libwpd-0.10-10
  libwpg-0.3-3 libwps-0.4-4 libxml++2.6-2v5 lp-solve module-assistant nvidia-firmware-535-535.171.04
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

### Relevant log output

With `Barrier > Change Settings > Enable SSL > OK > Ctrl+Q`

```shell
# flatpak run com.github.debauchee.barrier 
Gtk-Message: 08:29:02.116: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:29:02.117: Failed to load module "canberra-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: Could not open network socket
*** WARNING *** The program 'barrier' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
  OpenType support missing for "Ubuntu Mono", script 11
  OpenType support missing for "Ubuntu Mono", script 20
```

### Any other information

```
# printenv | grep XDG
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/home/k4nzdroid/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```
